
export const emotionalColors = [
  { color: '#FFD700', name: 'Joy', emotion: 'joy' },
  { color: '#4169E1', name: 'Sadness', emotion: 'sadness' },
  { color: '#FF0000', name: 'Anger', emotion: 'anger' },
  { color: '#32CD32', name: 'Disgust', emotion: 'disgust' },
  { color: '#800080', name: 'Fear', emotion: 'fear' },
  { color: '#FFA500', name: 'Surprise', emotion: 'surprise' },
  { color: '#FF69B4', name: 'Love', emotion: 'love' },
  { color: '#87CEEB', name: 'Peace', emotion: 'peace' },
  { color: '#98FB98', name: 'Hope', emotion: 'hope' },
  { color: '#DDA0DD', name: 'Anxiety', emotion: 'anxiety' },
  { color: '#F0E68C', name: 'Excitement', emotion: 'excitement' },
  { color: '#CD853F', name: 'Shame', emotion: 'shame' }
];

export const bodySensations = [
  { icon: 'butterfly', name: 'Nerves', color: '#9966CC' },
  { icon: 'Zap', name: 'Pain', color: '#FFD700' },
  { icon: 'Wind', name: 'Nausea', color: '#32CD32' },
  { icon: 'Droplet', name: 'Tears', color: '#4169E1' },
  { icon: 'Snowflake', name: 'Decreased Temperature', color: '#87CEEB' },
  { icon: 'Thermometer', name: 'Increased Temperature', color: '#FF4500' },
  { icon: 'Heart', name: 'Increased Heart Rate', color: '#FF1493' },
  { icon: 'Heart', name: 'Decreased Heart Rate', color: '#800080' },
  { icon: 'Wind', name: 'Tired', color: '#696969' },
  { icon: 'Activity', name: 'Change in Breathing', color: '#20B2AA' },
  { icon: 'Star', name: 'Tingling', color: '#FFD700' },
  { icon: 'Activity', name: 'Shaky', color: '#FF6347' },
  { icon: 'Droplet', name: 'Pacing', color: '#4682B4' },
  { icon: 'Activity', name: 'Stomping', color: '#8B4513' },
  { icon: 'Wind', name: 'Tight', color: '#2F4F4F' },
  { icon: 'Sparkles', name: 'Lump in Throat', color: '#9ACD32' },
  { icon: 'Activity', name: 'Change in Appetite', color: '#FF8C00' },
  { icon: 'Wind', name: 'Heaviness', color: '#708090' },
  { icon: 'Activity', name: 'Fidgety', color: '#DC143C' },
  { icon: 'Snowflake', name: 'Frozen/Stiff', color: '#B0C4DE' },
  { icon: 'Zap', name: 'Ache', color: '#8B4513' },
  { icon: 'Star', name: 'Feeling Small', color: '#A9A9A9' },
  { icon: 'Droplet', name: 'Dry Mouth', color: '#DEB887' },
  { icon: 'Activity', name: 'Clenched', color: '#B22222' },
  { icon: 'Zap', name: 'Change in Energy', color: '#FFD700' },
  { icon: 'Activity', name: 'Avoiding Eye Contact', color: '#9370DB' },
  { icon: 'Activity', name: 'Scrunched Face', color: '#CD853F' },
  { icon: 'Snowflake', name: 'Goosebumps', color: '#E6E6FA' },
  { icon: 'Wind', name: 'Relaxed', color: '#98FB98' },
  { icon: 'Droplet', name: 'Sweat', color: '#4682B4' }
];
